- name: Play Book1
  hosts: all
# Defined variable
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
# calling variable
         msg: URL = {{URL}}


- name: Book2
  hosts: all
  roles:
    -demo
  vars:
    URL: sample.notepad.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}

