- name: Play Book1
  hosts: all
# Defined variable
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
# calling variable
         msg: URL = {{URL}}

- name: Task Variable
  hosts: all
  vars:
    URL: sample.notepad.com
  tasks:
    ansible.builtin.debug:
     msg: URL = {{URL}}

